POST {{host}}/book
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzI2OTA5NDgsImV4cCI6MTczMjc3NzM0OCwiZW1haWwiOiJ0cnVvbmczQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.1cpjEAo-Fk-e75WN8SDUcSX1ESxeOuurtk19uEOAAPjhnYd8UpnbwlcebULEqUPQ

{
  "title": "Tinh Thần Biến",
  "author": "Nhĩ căn",
  "category": "Tiên hiệp"
}

###
PUT {{host}}/book/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzMyOTM2MDcsImV4cCI6MTczMzM4MDAwNywiZW1haWwiOiJ0cnVvbmczQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.ppBf73ZMM9E3v7iTwpFB1h0xdach6grA2xta2QV5dz4yNOSG6w47joONiamGMc_N

true

###
DELETE {{host}}/book/1

###
GET {{host}}/book
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzMyOTM2MDcsImV4cCI6MTczMzM4MDAwNywiZW1haWwiOiJ0cnVvbmczQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9BRE1JTiJ9.ppBf73ZMM9E3v7iTwpFB1h0xdach6grA2xta2QV5dz4yNOSG6w47joONiamGMc_N
#Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzMyOTM0NTEsImV4cCI6MTczMzM3OTg1MSwiZW1haWwiOiJuZ3V5ZW4yQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9DVVNUT01FUiJ9.oagtkNZZ6nxKNq1_EZNEcaPejHtDKoNDW-SEJwaIaQjJ8KZp6_KSyJAxbc8yTg2S
###
GET {{host}}/book/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpYXQiOjE3MzMyOTM0NTEsImV4cCI6MTczMzM3OTg1MSwiZW1haWwiOiJuZ3V5ZW4yQGdtYWlsLmNvbSIsImF1dGhvcml0aWVzIjoiUk9MRV9DVVNUT01FUiJ9.oagtkNZZ6nxKNq1_EZNEcaPejHtDKoNDW-SEJwaIaQjJ8KZp6_KSyJAxbc8yTg2S

###
GET https://aia-one.atlassian.net/rest/api/2/search?jql=assignee%20IN%20(5fbb3156aa1d30006ff2799d%2C%2062fc55535fc3a72bda944d9a%2C%2062fdbcaa43e43992b9a2fb4e%2C%20712020%3Ad38bbaf3-2b1a-454b-8da3-f8f320a5ce45%2C%20712020%3Abbc7a667-0d86-4fde-9faa-2ae826f0f1c4%2C%20712020%3Ab9088dd5-c814-4bfa-8770-659099ccd1e3%2C%20627dd3266ba8640069cfb086%2C%206269120434b9b700687b3b7c%2C%206417d9fd67102fc717c09586)AND%20project%20IN%20(AD%2C%20CS%2C%20PD%2C%20POS%2C%20OS)%20AND%20status%20IN%20(Closed%2C%20Escalated%2C%20%22In%20Progress%22%2C%20%22In%20Progress%22%2C%20Open%2C%20Pending%2C%20Reopened%2C%20Resolved%2C%20%22Waiting%20for%20customer%22%2C%20%22Waiting%20for%20support%22%2C%20Done)AND%20created%20%3E%3D%20%222024-09-01%22%20AND%20type%20IN%20(Problem%2C%20Support%2C%20Bug)%20AND%20created%20%3C%3D%20%222024-09-24%22%20ORDER%20BY%20resolution%20ASC%2C%20created%20DESC&startAt=0&maxResults=100
Authorization: Basic dGhhbmgta2hhbmgubGVAYWlhLmNvbTpBVEFUVDN4RmZHRjBiX0Vyb2lYUTQzSms0UmlEZmhDN3p4bGowam9OQnhxaXFhNWE4UGQtRWgzLXBGZmxLOTBPT0I4Zk1TMi1aWXhSV212aXFXTmhIQnFMZzRhVklVZWo1WS16b3BkS3pVYUVpMEJWSWpQSzBGUGZoTGtuMGxTQUJvMG5CRVhILS1xemhvNHJVWjN2bnJCQWIyWmRaZUF2SktUdnlwcE90Yi1KQUw0ZHpZVGJuMzg9OUM0NEU5NDE=